--Examining tables
SELECT *
FROM dbo.[2018]

SELECT *
FROM dbo.[2019]

SELECT *
FROM dbo.[2020]

--Creating table and unifying all the three tables and inserting it into the temp table for Exploratory data analysis

WITH Hotels as
(
SELECT *
FROM dbo.[2018]
UNION
SELECT *
FROM dbo.[2019]
UNION
SELECT *
FROM dbo.[2020] )

SELECT *
FROM Hotels

                   --------------EXPLORATORY DATA ANALYSIS---------------

--Looking at the revenue generated by different hotel types for each year
WITH Hotels as
(
SELECT *
FROM dbo.[2018]
UNION
SELECT *
FROM dbo.[2019]
UNION
SELECT *
FROM dbo.[2020] )

SELECT hotel,arrival_date_year,ROUND(
sum((stays_in_weekend_nights + stays_in_week_nights)*adr),2)as revenue --adr is per day rent of the hotel
FROM Hotels
GROUP BY hotel,arrival_date_year


--Joining the meal_cost table and market_segment table to find the cost for different meals and discount offered for different market segments
WITH Hotels as
(
SELECT *
FROM dbo.[2018]
UNION
SELECT *
FROM dbo.[2019]
UNION
SELECT *
FROM dbo.[2020] )

SELECT *
FROM Hotels as h
LEFT JOIN market_segment as m
ON h.market_segment=m.market_segment
LEFT JOIN meal_cost as c
ON c.meal=h.meal




